[2024-08-07T15:07:58.772+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T15:07:58.805+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_anyone.plots manual__2024-08-07T15:06:16.301406+00:00 [queued]>
[2024-08-07T15:07:58.817+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_anyone.plots manual__2024-08-07T15:06:16.301406+00:00 [queued]>
[2024-08-07T15:07:58.818+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-07T15:07:58.881+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): plots> on 2024-08-07 15:06:16.301406+00:00
[2024-08-07T15:07:58.892+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=90) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-07T15:07:58.896+0000] {standard_task_runner.py:64} INFO - Started process 92 to run task
[2024-08-07T15:07:58.895+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_anyone', 'plots', 'manual__2024-08-07T15:06:16.301406+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/ETL_anyone.py', '--cfg-path', '/tmp/tmpa44xu1mq']
[2024-08-07T15:07:58.899+0000] {standard_task_runner.py:91} INFO - Job 70: Subtask plots
[2024-08-07T15:07:59.013+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_anyone.plots manual__2024-08-07T15:06:16.301406+00:00 [running]> on host 2e8a41f9b15c
[2024-08-07T15:07:59.211+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_anyone' AIRFLOW_CTX_TASK_ID='plots' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T15:06:16.301406+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-07T15:06:16.301406+00:00'
[2024-08-07T15:07:59.217+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T15:07:59.237+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T15:07:59.237+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/plots_dag.py", line 3, in main_plots_dag
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-08-07T15:07:59.255+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ETL_anyone, task_id=plots, run_id=manual__2024-08-07T15:06:16.301406+00:00, execution_date=20240807T150616, start_date=20240807T150758, end_date=20240807T150759
[2024-08-07T15:07:59.294+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 70 for task plots (No module named 'matplotlib'; 92)
[2024-08-07T15:07:59.312+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-07T15:07:59.341+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-07T15:07:59.365+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
