[2024-08-07T15:18:28.294+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T15:18:28.348+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_anyone.plots manual__2024-08-07T15:16:50.187953+00:00 [queued]>
[2024-08-07T15:18:28.362+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_anyone.plots manual__2024-08-07T15:16:50.187953+00:00 [queued]>
[2024-08-07T15:18:28.373+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-07T15:18:28.424+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): plots> on 2024-08-07 15:16:50.187953+00:00
[2024-08-07T15:18:28.443+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=83) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-07T15:18:28.447+0000] {standard_task_runner.py:64} INFO - Started process 85 to run task
[2024-08-07T15:18:28.446+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_anyone', 'plots', 'manual__2024-08-07T15:16:50.187953+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/ETL_anyone.py', '--cfg-path', '/tmp/tmpv1wrfkn9']
[2024-08-07T15:18:28.452+0000] {standard_task_runner.py:91} INFO - Job 76: Subtask plots
[2024-08-07T15:18:28.592+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_anyone.plots manual__2024-08-07T15:16:50.187953+00:00 [running]> on host 2e8a41f9b15c
[2024-08-07T15:18:28.945+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_anyone' AIRFLOW_CTX_TASK_ID='plots' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T15:16:50.187953+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-07T15:16:50.187953+00:00'
[2024-08-07T15:18:28.948+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T15:18:28.950+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T15:18:28.951+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/plots_dag.py", line 2, in main_plots_dag
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2024-08-07T15:18:28.970+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ETL_anyone, task_id=plots, run_id=manual__2024-08-07T15:16:50.187953+00:00, execution_date=20240807T151650, start_date=20240807T151828, end_date=20240807T151828
[2024-08-07T15:18:29.110+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 76 for task plots (No module named 'matplotlib'; 85)
[2024-08-07T15:18:29.147+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-07T15:18:29.183+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-07T15:18:29.209+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
